### ISSUE TITLE
Flytte opprette kunde til stored procedure i basen

### ISSUE THREAD

**Issue by CSkogbakken** [DanielTangnes/tverrfaglig-pr-ve#19]

**Comment by DanielTangnes** [comment]
Feilmelding når jeg kjører Ny_Kunde procedure.
Fornavn: test, Etternavn: test, adresse: test, postnr: 0021
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\danie\AppData\Local\Programs\Python\Python311\Lib\site-packages\mysql\connector\connection_cext.py", line 706, in cmd_query
    self._cmysql.query(
_mysql_connector.MySQLInterfaceError: Cannot add or update a child row: a foreign key constraint fails (`varehusdb`.`kunde`, CONSTRAINT `KundePoststedFN` FOREIGN KEY (`PostNr`) REFERENCES `poststed` (`PostNr`))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\danie\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\danie\PycharmProjects\tverrfaglig-pr-ve\main.py", line 145, in <lambda>
    opprett_kunde_cmd=lambda: opprette_kunde(fornavn_entry.get(), etternavn_entry.get(), adresse_entry.get(), postnr_combo.get()),
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\danie\PycharmProjects\tverrfaglig-pr-ve\main.py", line 107, in opprette_kunde
    cursor.callproc("Ny_Kunde", (fornavn, etternavn, adresse, postnr))
  File "C:\Users\danie\AppData\Local\Programs\Python\Python311\Lib\site-packages\mysql\connector\cursor_cext.py", line 566, in callproc
    result = self._connection.cmd_query(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\danie\AppData\Local\Programs\Python\Python311\Lib\site-packages\mysql\connector\opentelemetry\context_propagation.py", line 97, in wrapper
    return method(cnx, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\danie\AppData\Local\Programs\Python\Python311\Lib\site-packages\mysql\connector\connection_cext.py", line 714, in cmd_query
    raise get_mysql_exception(
mysql.connector.errors.IntegrityError: 1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`varehusdb`.`kunde`, CONSTRAINT `KundePoststedFN` FOREIGN KEY (`PostNr`) REFERENCES `poststed` (`PostNr`))

Process finished with exit code 0

**Comment by DanielTangnes** [comment]
Fikset ved å sette newPostNr til char:
CREATE DEFINER=`23ITDNett`@`%` PROCEDURE `Ny_Kunde`(
    IN newFornavn VARCHAR(255),
    IN newEtternavn VARCHAR(255),
    IN newAdresse VARCHAR(255),
    IN newPostNr char(4)
)
BEGIN
    DECLARE newKNr INT;

    -- Henter siste kundenummer og legger på 1
    SET newKNr = coalesce((SELECT MAX(KNr) FROM kunde), 0) + 1 ;

    -- Setter inn nytt kundenummer i ny rad, og oppdaterer resten av feltene med data fra programmet
    INSERT INTO kunde (KNr, Fornavn, Etternavn, Adresse, PostNr)
    VALUES (newKNr, newFornavn, newEtternavn, newAdresse, newPostNr);
END
